development:
  clients:
    default:
      database: <%= ENV.fetch('MONGODB_DATABASE', 'esmx_development') %>
      hosts:
        - <%= ENV.fetch('MONGODB_HOST', 'localhost') %>:<%= ENV.fetch('MONGODB_PORT', '27017') %>
      options:
        server_selection_timeout: 5
  options:
    raise_not_found_error: true

test:
  clients:
    default:
      database: esmx_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: <%= ENV.fetch('MONGODB_DATABASE', 'esmx_production') %>
      hosts:
        - <%= ENV.fetch('MONGODB_HOST', 'localhost') %>:<%= ENV.fetch('MONGODB_PORT', '27017') %>
      options:
        read:
          mode: :primary
        max_pool_size: 5
